### ISSUE TITLE
High effort to link content

### ISSUE THREAD

**Issue by silvia-br** [serlo/backlog#106]
**Problem**: It takes some effort to find the ID of the content that you want to link. For that reasons links are sometimes omitted.

**Request**: maybe it is possible to find a user-friendly compromise, e.g. when adding a link, there's an option to have all IDs of a certain topic (Themenbereich) shown.

**Stakeholder**: n/a

**Source**: old backlog - Google Docs

**Comment by elbotho** [comment]
There is already a proposal for this in the UX pipeline.

**Comment by elbotho** [comment]
There is now a seach tool when linking content in the editor
