### ISSUE TITLE
Exercise collections can't be edited as a whole 

### ISSUE THREAD

**Issue by silvia-br** [serlo/backlog#121]
**Problem**: in a exercise collection (Aufgabengruppe) it's only possible to edit each exercise individually (Teilaufgaben) and their solutions, but it's not possible to edit the entire collection as a whole

**Request**: possibility to edit exercise collections as a whole

**Source**: old backlog document

**Comment by elbotho** [comment]
Groups are indeed editable ([example](https://de.serlo.org/entity/repository/add-revision/133457)) so this is either a non issue or I did not understand the problem :D Feel free to reopen.
