### ISSUE TITLE
Long H5P Drag & Drop exercises don't work on mobile

### ISSUE THREAD

**Issue by silvia-br** [serlo/backlog#147]
**Description**
Long H5P Drag & Drop exercises don't work on mobile

**Links**
[Meldung auf Slack](https://serlo.slack.com/archives/C0BMSC431/p1685112163760259)

**Screenshot/Video**
[Video](https://serlo.slack.com/files/U012YV2838X/F05A2GWUB5F/h5p-handy-schwierigkeit.mp4)

Reproducible?
Yes

**Betriebssystem and Browser (incl. Version)**
n/a

**Error message from the browser console**
n/a

**Stakeholder**
Lina (+ responsible for H5P: Tina, Quinn)

**Comment by elbotho** [comment]
@Entkenntnis could you confirm that this is an upstream issue and we won't fix this? 
No sense in tracking it then :)

**Comment by Entkenntnis** [comment]
jup, it's upstream. Only way would be a contribution from our side ..
