### ISSUE TITLE
Image Plugin stays in focus after editing caption

### ISSUE THREAD

**Issue by silvia-br** [serlo/backlog#153]
**Problem**: after editing the caption of an image and clicking somewhere else, the image plugin keeps remaining in focus. This doesn't happen after editing the description or the URL of the image, but only for the caption

**Request**: focus on image plugin disappears after clicking away

**Source**: old backlog document

<img width="340" alt="image" src="https://github.com/serlo/backlog/assets/127129431/e1e08d97-e5f9-4455-9837-3646df0c6e86">

**Comment by elbotho** [comment]
@hejtful this is solved, right?

**Comment by hejtful** [comment]
Looks solved to me 👍
