### ISSUE TITLE
 Dnd issue in text-plugin: drag preview in Chrome doesn't handle absolute positioned elements

### ISSUE THREAD

**Issue by anbestCL** [serlo/backlog#159]
When dragging the text-plugin while the absolute positioned bottom-toolbar is visible, then the drag preview will display all the plugins between the dragged and the bottom-toolbar as well

![grafik](https://github.com/serlo/backlog/assets/43368821/c16e3838-2f4b-4d91-a61e-e3b4f097f6d9)

(Moved from edtr-io: https://github.com/edtr-io/edtr-io/issues/280)

**Comment by hejtful** [comment]
Fixed by the new plugin toolbar.
