### ISSUE TITLE
More precise date/time for edits

### ISSUE THREAD

**Issue by silvia-br** [serlo/backlog#167]
**Problem**: edits don't have a precise date and time, but normally something like "2 weeks ago"

**Request**: more precise info about date and time of the edits

**Source**: old backlog document

**Comment by elbotho** [comment]
Closing this as not specific enough. 
The dates that are displayed as "2 weeks ago" can all be hovered to get the accurate date (in the title attr).
If there is a view where a more accurate date is always needed, please reopen.
