### ISSUE TITLE
[LENABI Milestone] M2.2 "Ein Migrationsalgorithmus für das Speicher- und Austauschformat ist implementiert. (Dieser ermöglicht, dass parallel neue Lerninhalte für den Editor entwickelt werden können und Lerninhalte im Speicher- und Austauschformat standardisiert werden können.) "

### ISSUE THREAD

**Issue by sesa929** [serlo/backlog#19]
![](https://github.trello.services/images/mini-trello-icon.png) [Austauschformat für Serlo-Editor](https://trello.com/c/i6qArflE/29-austauschformat-f%C3%BCr-serlo-editor)

Since we want to include the Serlo editor in other learning management systems we will have Serlo content outside our scope in databases we have no access to. Thus we cannot use DB migrations (see https://github.com/serlo/serlo.org-legacy/tree/main/packages/migrations) whenever the content format has changes. Thus we need other mechanism to ensure that a Serlo content can be always read in the future even if our plugins have changed in the meanwhile (some plugins became deprecated or properties of a plugin has changed).

Thus we need to find an answer to the question: How can we make sure that any Serlo content which is stored somewhere in an LMS can also be read in the future (even after further developments in the editor)? The result might be a solution + a roadmap for achieving it.

Repo: https://github.com/serlo/lenabi-migration-algorithm

- [x] #71 
- [x] #73 
- [x] #74
- [x] #80

**Comment by kulla** [comment]
Work document: https://docs.google.com/document/d/1zn9CD-jKQ7jZzULisgYERVFK7oLidJepgaOiT2gybls/edit

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Austauschformat für Serlo-Editor](https://trello.com/c/i6qArflE/29-austauschformat-f%C3%BCr-serlo-editor)

**Comment by Entkenntnis** [comment]
result in https://github.com/serlo/lenabi-migration-algorithm

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [M2.2 Ein Migrationsalgorithmus für das Speicher- und Austauschformat ist implementiert. (Dieser ermöglicht, dass parallel neue Lerninhalte für den Editor entwickelt werden können und Lerninhalte im Speicher- und Austauschformat standardisiert werden können.)](https://trello.com/c/HwuFajj7/44-m22-ein-migrationsalgorithmus-f%C3%BCr-das-speicher-und-austauschformat-ist-implementiert-dieser-erm%C3%B6glicht-dass-parallel-neue-lernin)

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [M2.2 Ein Migrationsalgorithmus für das Speicher- und Austauschformat ist implementiert. (Dieser ermöglicht, dass parallel neue Lerninhalte für den Editor entwickelt werden können und Lerninhalte im Speicher- und Austauschformat standardisiert werden können.)](https://trello.com/c/HwuFajj7/44-m22-ein-migrationsalgorithmus-f%C3%BCr-das-speicher-und-austauschformat-ist-implementiert-dieser-erm%C3%B6glicht-dass-parallel-neue-lernin)
