### ISSUE TITLE
Add dependabot in all main repositories of serlo

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#196]
Add dependabot in all main repositories. Example: https://github.com/serlo/api.serlo.org/blob/main/.github/dependabot.yml

### For each repo

* Add updates for npm and docker
* Add updates for 

### Repositories

- [x] https://github.com/serlo/database-layer
  - Update rust dependencies as well
- [x] https://github.com/serlo/api.serlo.org
- [x] serlo/cloudflare-worker#418
- ~https://github.com/serlo/frontend~
- ~https://github.com/serlo/frontend-e2e-tests~
- [x] https://github.com/serlo/db-migrations
- ~https://github.com/serlo/serlo-editor-for-edusharing~
- [x] https://github.com/serlo/notification-mail-service

### Blocker

- [x] https://github.com/serlo/backlog/issues/205

**Comment by Entkenntnis** [comment]
In the frontend, I would prefer to update dependencies manually: dependabot is creating imho too much noise.

We have security alerts enable, so all security relevant updates will already generate a dependabot PR.

**Comment by AndreasHuber** [comment]
@Entkenntnis @LarsTheGlidingSquirrel you said no for [frontend](https://github.com/serlo/frontend) and [frontend-e2e-tests](https://github.com/serlo/frontend-e2e-tests). 
I assume the same for [serlo-editor-for-edusharing](https://github.com/serlo/serlo-editor-for-edusharing)?

So then I only open a PR for https://github.com/serlo/notification-mail-service and then this ticket is done.

**Comment by LarsTheGlidingSquirrel** [comment]
> I assume the same for [serlo-editor-for-edusharing](https://github.com/serlo/serlo-editor-for-edusharing)?

Since `serlo-editor-for-edusharing` uses `frontend` in many places, I think it makes sense to use the same approach. So no dependabot for now. I'll message you when we decide otherwise.
