### ISSUE TITLE
[LENABI MILESTONE] M.2.1 Entwurf für die allgemeine Grundstruktur des Aufgaben- und Austauschformats steht und ist in einem Open Source Repository veröffentlicht.

### ISSUE THREAD

**Issue by sesa929** [serlo/backlog#20]
Repo: https://github.com/serlo/lenabi-exchange-format

- [x] #75 
- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #89

**Comment by kulla** [comment]
~Merged with #18~

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [M2.1 Austauschformat für Serlo-Editor](https://trello.com/c/i6qArflE/29-m21-austauschformat-f%C3%BCr-serlo-editor)

**Comment by Entkenntnis** [comment]
@sesa929 all tasks done, can be closed

**Comment by kulla** [comment]
> @sesa929 all tasks done, can be closed

yep
