### ISSUE TITLE
Add `yarn upgrade-interactive` in all repositories

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#201]
See https://github.com/yarnpkg/berry/blob/HEAD/packages/plugin-interactive-tools/README.md

Even if the yarn plugin `interactive-tools` is already installed, executing `yarn plugin import interactive-tools` might install a newer version. 

Add or update yarn plugin `interactive-tools`:

- [x] https://github.com/serlo/database-layer
- [x] https://github.com/serlo/api.serlo.org
- [x] https://github.com/serlo/cloudflare-worker
- [x] https://github.com/serlo/frontend
- [x] serlo/frontend-e2e-tests#36
- [x] serlo/db-migrations#65
- [x] https://github.com/serlo/serlo-editor-for-edusharing
- [x] Add yarn upgrade-interactive in https://github.com/serlo/notification-mail-service

**Comment by eliflores** [comment]
Done 💚
