### ISSUE TITLE
Upgrade GitHub-Actions to most current version (also do small refactorings)

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#206]
Take for example https://github.com/serlo/api.serlo.org/blob/9c1037a3b8b3517553c0a9a705dfd8e4b2deb6ab/.github/workflows/js.yml#L12 . When we have a look at https://github.com/actions/setup-node we see that it is currently in version v3 and not V2. Have a look at the Changelog for each action like https://github.com/actions/setup-node/releases/tag/v3.0.0 to see whether we need to change something 

While you look at the actions: Can they be rewritten in a better way?

List of repositories (without checking whether this was already done):

- [x] serlo/database-layer#463
- [x] https://github.com/serlo/api.serlo.org (see comment https://github.com/serlo/backlog/issues/206#issuecomment-1607427194)
- [x] https://github.com/serlo/cloudflare-worker/issues/392
- [x] https://github.com/serlo/frontend (actions in this repository are up to date).
- [x] https://github.com/serlo/frontend-e2e-tests (no GitHub Actions)
- [x] serlo/db-migrations#39
- [x] https://github.com/serlo/serlo-editor-for-edusharing (PR: https://github.com/serlo/serlo-editor-for-edusharing/pull/274)
- [x] https://github.com/serlo/notification-mail-service (Added GitHub Actions dependabot updates in https://github.com/serlo/notification-mail-service/pull/42, after which dependabot opened PRs for the actions that needed to be updated, and these PRs have been merged).

**Comment by eliflores** [comment]
* About: https://github.com/serlo/api.serlo.org: Added GitHub Actions dependabot updates in https://github.com/serlo/api.serlo.org/pull/898, after which dependabot opened PRs for the actions that needed to be updated. Also refactored the Docker workflow for PR events in: https://github.com/serlo/api.serlo.org/pull/876.
