### ISSUE TITLE
Update all dependencies in our main repositories

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#208]
- [x] #207 
- [x] #206 
- [x] #205 
- [x] #203 
- [x] #202 
- [x] #201 
- [x] #200 
- [x] #199 
- [x] #198 
- [x] #197 
- [x] #196

**Comment by kulla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update dependencies unserer wichtigsten Repositories](https://trello.com/c/GQD8SU0i/82-update-dependencies-unserer-wichtigsten-repositories)

**Comment by AndreasHuber** [comment]
I am working on database-layer currently but anyone feel free to look at the other repos.

**Comment by kulla** [comment]
I close it, since it is a duplicate of the view https://github.com/orgs/serlo/projects/34/views/6
