### ISSUE TITLE
☂️ Presentation website for serlo-editor

### ISSUE THREAD

**Issue by sesa929** [serlo/backlog#21]
![](https://github.trello.services/images/mini-trello-icon.png) [Präsentations-Website für Serlo-Editor](https://trello.com/c/xywVhqwS/28-als-potentieller-editor-adaptor-besuche-ich-die-pr%C3%A4sentations-website-um-mich-davon-zu-%C3%BCberzeugen-wie-m%C3%A4chtig-der-serlo-editor-i)

As potential adaptor i visit the presentation website to convince myself of how powerful the serlo-editor is and how easy it can be adapted to my LMS

## TODOs

- [x] #45
- [x] #46
- [x] #47
- [x] #48
- [x] #49
- [x] #50
- [x] #51
- [x] ~#52~
- [x] #70
- [x] #72

**Comment by jthedens** [comment]
Inhaltssammlung und Prototype:
https://miro.com/app/board/uXjVP1ClBeM=/

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Präsentations-Website für Serlo-Editor](https://trello.com/c/xywVhqwS/28-als-potentieller-editor-adaptor-besuche-ich-die-pr%C3%A4sentations-website-um-mich-davon-zu-%C3%BCberzeugen-wie-m%C3%A4chtig-der-serlo-editor-i)
