### ISSUE TITLE
Use `serlo-mysql-database` image where it is needed

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/backlog#250]
Now that we have a unified way of creating our test database in the repo serlo/serlo-mysql-database we don't need to repeat the setup in may repos, but just pull the image.

- [x] serlo/evaluations#13
- [x] serlo/database-layer#517
- [x] serlo/serlo-bot#13
- [x] Use serlo/serlo-mysql-database in local-dev-env - done in https://github.com/serlo/local-dev-env/pull/16
- [x] notification-mail-service - done in https://github.com/serlo/notification-mail-service/pull/71

**Comment by eliflores** [comment]
Done 💚
