### ISSUE TITLE
Archive KPI repositories and delete KPI services from our infrastructure

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#285]
These repositories and services were used to develop the KPI project. However, either the KPI project is either not developed anymore, or this custom tooling is not necessary to develop the KPI project anymore.

## RICE Score
- Reach and impact: **2** -- Nobody will really notice this in their day-to-day work but there will be less repos in the Serlo GitHub organization, and there will be fewer modules in Terraform.
- Confidence: **10** -- We have full control over our GitHub and Terraform.
- Effort: **1** -- Archiving GitHub repos is just a couple of clicks, and removing Terraform modules is just removing a few files and deleting a few lines of code.

**Comment by kulla** [comment]
Effected repos: 

![Image](https://github.com/serlo/backlog/assets/1327215/1914046b-1f16-4ee0-9036-40e05769f441)

Other stuff:

* Deletetion of our postgress DB in backend
* Fewer cronjobs and containers in infrastructure

**Comment by hugotiburtino** [comment]
> Deletetion of our postgress DB in backend

Just deleting the postgres isn't possible yet, since it has also our Kratos database. The rest is done
