### ISSUE TITLE
Simplify internal software architecture and development in API

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#286]
- Permission lib: https://github.com/orgs/serlo/projects/40/views/1?pane=issue&itemId=37591328
- ...

**Comment by kulla** [comment]
Unfortunately this need to be planned, so no idea how much time it will cost -> @AndreasHuber @hejtful Here for the impact you need to think how much developing in the API is annoying...

**Comment by hugotiburtino** [comment]
This would be an umbrella issue, but I think we should discuss it in slack instead of having such a big topic and discussion in Github. So closing...
