### ISSUE TITLE
Automatic deployment of microservices

### ISSUE THREAD

**Issue by AndreasHuber** [serlo/backlog#289]
To implement a new feature with a database change like a new table, currently requires a lot of manual release creation and deployment: db-migration - also including applying the change to the test database -, database-layer, API gateway.
Automatized/continuous deployment would therefore save developer time and especially also from our more senior developer who are mostly doing the deployment.
The idea here is that on merge of a feature branch to main, we have automatic deployment to staging. Deployment to production also does not happen manually but can be triggered by project admins on Github via clicking a button.

There are two different ideas how to reach this goal.

1. Helm

The first one is to use [helm](https://helm.sh/) instead of Terraform to deploy an application / service (such as [content-generation-service](https://github.com/serlo/content-generation-service)). So what was done in [infrastructure-modules-api](https://github.com/serlo/infrastructure-modules-api/blob/main/content-generation-service/main.tf) in the PRs:
- https://github.com/serlo/infrastructure-env-staging/pull/61
- https://github.com/serlo/infrastructure-env-staging/pull/62
could be done instead using helm to package the Kubernetes manifests, and have the deployment pipeline in the repository itself, in GitHub Actions. [This](https://github.com/deliverybot/example-helm/) is an example project for how that could work.

2. No Helm

The likely easier approach is to push a container on every merge and trigger a deployment job that will always deploy the most recent container. This approach does not need the addition of yet another new thing to know for developers, Helm, and should be less change compared to our current status. So this option is currently our favorite that we want to implement, Option 1 is listed for completeness.

Suggestion from Andi: [Start implementing continuous delivery (CD) with a service that we do not plan to change otherwise like notification-mail-service. After we know how that works, we can then proceed with the important ones (API/database-layer).](https://docs.google.com/document/d/18o691FGWoNifggtjr_aU7NWYqnSXkqi5l9wcCUvFi_U/edit#bookmark=id.m80oochihlxm)

Before implementing this for database-layer and the API gateway, it would be useful to know if those stay separate repositories or we want to merge them into a monorepo. 

## RICE Score

- Reach and Impact: **8** -- Currently mainly Hugo and Kulla do deployment whose time might be very valuable elsewhere. Also it would remove some wait time or time that newer developers need to figure out how to make a release and deploy to staging.
- Confidence: **10** -- It's something that most web companies are doing, and we even have an example repository where it's done. It could be tricky, but there's nothing special about our services, that would block us in implementing this.
- Effort: **5** -- Not super trivial but good idea of what has to be done and can be done by one person.

**Comment by kulla** [comment]
Something which wee need to keep in mind: Sometimes we have a PR we want to test in staging but we cannot deploy in production yet (for example a change in the API which need to be reflected in frontend yet). So we need to find a way that we have a `staging` version which cannot be deployed fully to `production` but we want to merge some PRs there (for example for bugfixes or other PRs which are ready for deployment)

**Comment by hugotiburtino** [comment]
> Sometimes we have a PR we want to test in staging but we cannot deploy in production yet

In that case, I would suggest to have a `release-candidate` branch (or simply `rc`. We could even keep `main`), meaning it receives the commits we are quite sure it can go anytime to production. 

We would primarily work on this branch and then merge into `staging` and `production`. 
In case we have v.g. a special feature that should be tested long time in `staging` first, we would merge PRs directly into `staging`. After we are done, we could then merge `staging` into `release-candidate` and `production`.

**Comment by hugotiburtino** [comment]
Let me illustrate how it could work

- In api.serlo.org and database-layer repos (the only repos that has regular releases in backend)
- The image pull policy is set to always.
- In staging cluster the image tag is staging, in production production
- Everytime it is merged into staging or production branch, a GH Action creates a new image and tags it as staging or production, respectively
- After the tagging, another GH Action runs a simple `kubectl` to delete the pod, assuming it will get the newest image (Disclaimer: to be honest, I haven't studied the documentation to see if it would be so easy.).

One thing to have in mind: some features need migrations. Let's think later about how to couple automatic deployment with migration.
