### ISSUE TITLE
Less infrastructure code repositories

### ISSUE THREAD

**Issue by AndreasHuber** [serlo/backlog#296]
We currently have ~10 repos with infrastructure things: https://github.com/orgs/serlo/repositories?language=&q=infra
This presents the following disadvantages:
- hard for new developers to get an overview or know where to put changes
- infrastructure changes very often require working on 2 repos at the same time
- to check changes with terraform plan, you always to point to your local repo and then revert that before committing

Therefore, it might simplify things to merge infrastructure repos together. 

Suggestions:
1. Put really all repos in just one (advantage: total simplification, disadvantage: the tagging of the repos would may be hard to handle) 
2. Put just the module repos in one and leaving the env as they are (advantage: tagging is simpler than suggestion 1; disadvantage: not total merging of repos).

## RICE Score

- Reach and Impact: **6** -- Would make it easier for developers to work on infrastructure related PRs.
- Confidence: **9** -- Clearly possible, just have to see how exactly it makes sense.
- Effort: **2** -- It is really just about reordering the repos, no real change in the infra

**Comment by kulla** [comment]
Done by @hugotiburtino :heart:
