### ISSUE TITLE
Replace api, db layer, db-migrations (and maybe kratos) with an up-to-date fullstack framework (v.g. Django)

### ISSUE THREAD

**Issue by AndreasHuber** [serlo/backlog#297]
Open questions:
- What is the difference to [combining API gateway and database-layer](https://github.com/orgs/serlo/projects/40/views/1?pane=issue&itemId=37218356)?
- Why the focus on the framework, do we have problems with a particular framework?
- What is our criteria, when choosing a framework?

## RICE Score
- Reach: **N** -- Why?
- Impact: **N** -- Why?
- Confidence: **N** -- Why?
- Effort: **N** -- Why?

**Comment by hugotiburtino** [comment]
close as rejected
