### ISSUE TITLE
☂️  Merge `Course` and `CoursePage`

### ISSUE THREAD

**Issue by elbotho** [serlo/backlog#301]
### intro
similar to moving solutions into [the editor state of the parent exercise](https://github.com/serlo/db-migrations/pull/181) we want to move the course pages into the editor state of the parent course.

### why?
- simplify backend and entities
- simplify reviewing
- hopefully less bugs

### impact
Last entity with entity children. Finishing this will unlock a lot of simplifications across our codebase

### potential problems
- we use the coursePage urls directly quite a bit
- we have to handle SEO
- ~editing experience might be annoying for long courses~ ([solved here](https://github.com/serlo/frontend/pull/3543))

### plan/unclear
- [ ] find a way to link to page directly after migration (like GroupedEx)
- Note: not supporting injections is probably ok ([source](https://nbviewer.org/github/serlo/evaluations/blob/eab1dc7a2af6568f78d30790ad5477690acc866e/src/2023/2023-11-02-injection-of-solutions.ipynb#section1)) (but could be supported like we do with GroupedEx)
- [ ] change existing links and relatedContent (db-migration)
- [x] improve edit UI so it's not overwhelming for long courses? ([solved here](https://github.com/serlo/frontend/pull/3543))

### migrate
- [ ] update course editor state in frontend
- [ ] build migration to move all course pages into the parent courses editor state
- adapt frontend
  - [ ] show pages from state
  - [ ] change how urls are created
  - [ ] change author menus
  - [ ] remove CoursePage entity code
  - …
- [ ] add redirect in cf-worker to 301 previously existing coursePage links and remove existing course redirects
- [ ] test changes

### cleanup
- [ ] remove code from api
- [ ] remove code from db layer
- [ ] delete coursePages from db (migration)

#### links
We need to think about way to directly 
we should def. update existing links

**Comment by Entkenntnis** [comment]
SEO would be the biggest task: About 9% of our total traffic are course pages and most of the time it's not the first page, but some other page like https://de.serlo.org/mathe/20322/addition-und-subtraktion-ungleichnamige-brüche. Course pages are de-facto "mini articles".

The most painless path here would be to keep all urls backward compatible - the very least to redirect them so that google can find them.

**Comment by elbotho** [comment]
closing in favour of https://github.com/serlo/db-migrations/issues/338
