### ISSUE TITLE
Check whether we can use prometheus in Gcloud already

### ISSUE THREAD

**Issue by kulla** [serlo/backlog#319]
See 
![2024-03-21-204043_574x612_scrot](https://github.com/serlo/backlog/assets/1327215/9f099fc8-d2c0-4a64-a9a2-1f9c68f2fd1f)

**Comment by hugotiburtino** [comment]
I think we shouldn't make any effort here since our objective by simplifying the backend is to reduce or even remove kubernetes from the infrastructure
