### ISSUE TITLE
First tests with another images registry

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/backlog#329]
The container registry of google cloud is already deprecated and will be completely shut down

> Container Registry is deprecated and scheduled for shutdown. After May 15, 2024, Artifact Registry will [host images for the gcr.io domain by default ](https://cloud.google.com/artifact-registry/docs/transition/gcr-on-ar) in projects without previous Container Registry usage. After March 18, 2025, Container Registry will be shut down.

Now, we could change to other Google Cloud service, but first we could check if the Github itself. 

Tasks: 
- [x] Investigate which costs and limitations it could have to migrate the images to Github artifacts
- [x] If ok enough, make an example, deploying it to github and fetching it from here
- [x] The example could also contain how to integrate it in CI

**Comment by AndreasHuber** [comment]
Limitations: 
- Pulling an image from the public net and therefore deployments will be a bit slower than with images stored in GCR.
- Github artifacts are stored for [90 days for public repositories](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#artifact-and-log-retention-policy).

Costs:
- Usage of Github artifacts does seem without cost for public repositories.
- [Google does not charge for inbound traffic](https://cloud.google.com/vpc/network-pricing#general_network_pricing), so that pulling the image from outside should not increase costs from Google.

**Comment by hugotiburtino** [comment]
thanks for the initial researches

> Github artifacts are stored for [90 days for public repositories](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#artifact-and-log-retention-policy).

That would be a No-go to this change. However, I suppose Github has a way to store the images forever, as I see it from other repositories. Could you take a look at [github packages](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages) then and investigate the limitations?

**Comment by AndreasHuber** [comment]
Why would you need to store Docker images forever? Even if you really want to go far back, you could always re-run the pipeline for an old commit to re-create the image, no?

**Comment by AndreasHuber** [comment]
https://github.com/orgs/community/discussions/21973 sounds like there is no cost or storage limit for using the Github Container Registry but changes to this can occur in the future (with >= 30 days notice).

**Comment by hugotiburtino** [comment]
> Why would you need to store Docker images forever? Even if you really want to go far back, you could always re-run the pipeline for an old commit to re-create the image, no?

Point taken, you are right that we don't need the images forever. So, I changed my mind and agree that it is still an option.

I just thing that 90 days is quite a short time. Since we use the `pull_policy: "Always"` a lot, I could imagine the following case: we need to restart the api after 90 days, for a very simple fix, and instead we have to take some time rebuilding the image and so on. So, what should be simple ends up being an unnecessary time consuming task. I think 1 year retention policy is a quite good period.

**Comment by AndreasHuber** [comment]
Anyways, GHCR seems to work so I have used that instead of Github artifacts that are deleted after 90 days.
