### ISSUE TITLE
Add missing title / label attributes

### ISSUE THREAD

**Issue by inyono** [serlo/backlog#44]
- [ ] https://github.com/serlo/serlo.org/pull/182#discussion_r373337979
- [ ] https://github.com/serlo/serlo.org/pull/182#discussion_r373338035
- [ ] https://github.com/serlo/serlo.org/pull/182#discussion_r373338063
- [ ] https://github.com/serlo/serlo.org/pull/182#discussion_r373338077
- [ ] https://github.com/serlo/serlo.org/pull/182#discussion_r373339241

**Comment by hugotiburtino** [comment]
Still relevant?

**Comment by kulla** [comment]
> Still relevant?

I would say, we will figure it out, when we do #24
