### ISSUE TITLE
More noticable button for adding a new plugin

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/backlog#96]
Linked to https://trello.com/c/7d1eREVQ/90-auff%C3%A4lliger-hinzuf%C3%BCgen-button

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auffälliger Hinzufügen Button](https://trello.com/c/7d1eREVQ/90-auff%C3%A4lliger-hinzuf%C3%BCgen-button)
